const {url,key}=BANLANG;let token=localStorage.getItem('banlang_token')||'';const H=()=>({apikey:key,Authorization:'Bearer '+(token||key),'Content-Type':'application/json',Prefer:'return=representation'});
async function req(path,opt={}){const r=await fetch(url+path,{...opt,headers:{...H(),...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());const t=await r.text();return t?JSON.parse(t):[]}
async function login(email,password){const r=await fetch(url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw Error('อีเมลหรือรหัสผ่านไม่ถูกต้อง');const x=await r.json();token=x.access_token;localStorage.setItem('banlang_token',token);if(x.refresh_token)localStorage.setItem('banlang_refresh',x.refresh_token)}
async function refreshSession(){try{const refresh=localStorage.getItem('banlang_refresh');if(!refresh)return false;const r=await fetch(url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh})});if(!r.ok)return false;const x=await r.json();token=x.access_token;localStorage.setItem('banlang_token',token);if(x.refresh_token)localStorage.setItem('banlang_refresh',x.refresh_token);return true}catch(e){return false}}
async function session(){if(!token)return false;let r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+token}});if(r.ok)return true;if(await refreshSession()){r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+token}});return r.ok}return false}
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function boot(){if(await session()){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');await loadAll()}else{$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await login($('#email').value,$('#password').value);await boot()}catch(x){$('#loginMsg').textContent=x.message}};
$('#logout').onclick=()=>{localStorage.removeItem('banlang_token');localStorage.removeItem('banlang_refresh');token='';boot()};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#pageTitle').textContent=b.textContent});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function loadAll(){const [p,r,s,settings]=await Promise.all([req('/rest/v1/portfolio?select=*&order=sort_order.asc,created_at.desc'),req('/rest/v1/pricing?select=*&order=sort_order.asc'),req('/rest/v1/services?select=*&order=sort_order.asc'),req('/rest/v1/site_settings?select=*')]);window.rows={p,r,s,settings};$('#portfolioCount').textContent=p.length;$('#priceCount').textContent=r.length;$('#serviceCount').textContent=s.length;
$('#portfolioList').innerHTML=p.map(x=>`<div class="row"><div><h3>${esc(x.title)}</h3><p>${esc(x.scope||'-')}</p><span class="tag">${x.published?'เผยแพร่':'ซ่อน'} · ${esc(x.category||'ไม่ระบุหมวด')}</span></div><div class="row-actions"><button class="muted" onclick="editP(${x.id})">แก้ไข</button><button class="danger" onclick="del('portfolio',${x.id})">ลบ</button></div></div>`).join('');
$('#priceList').innerHTML=r.map(x=>`<div class="row"><div><h3>${esc(x.service)}</h3><p>${esc(x.starting_price||'-')} · ${esc(x.unit_price||'-')}</p></div><div class="row-actions"><button class="muted" onclick="editR(${x.id})">แก้ไข</button><button class="danger" onclick="del('pricing',${x.id})">ลบ</button></div></div>`).join('');
$('#serviceList').innerHTML=s.map(x=>`<div class="row"><div><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p></div><div class="row-actions"><button class="muted" onclick="editS(${x.id})">แก้ไข</button><button class="danger" onclick="del(\'services\',${x.id})">ลบ</button></div></div>`).join('');fillSettings(settings)}
$('#newPortfolio').onclick=()=>{ $('#portfolioForm').reset();$('#pId').value='';$('#pFeatured').checked=false;$('#pPublished').checked=true;$('#portfolioImagePreview').innerHTML='';$('#portfolioDialog').showModal()};$('#newPrice').onclick=()=>{$('#priceForm').reset();$('#rId').value='';$('#rPublished').checked=true;$('#priceDialog').showModal()};$('#newService').onclick=()=>{$('#serviceForm').reset();$('#sId').value='';$('#sPublished').checked=true;$('#serviceImagePreview').innerHTML='';$('#serviceDialog').showModal()};
window.editP=async id=>{const x=rows.p.find(v=>v.id==id);$('#pId').value=x.id;$('#pTitle').value=x.title;$('#pScope').value=x.scope||'';$('#pCategory').value=x.category||'';$('#pYear').value=x.year||'';$('#pLocation').value=x.location||'';$('#pDescription').value=x.description||'';$('#pFeatured').checked=!!x.featured;$('#pPublished').checked=x.published;$('#portfolioImagePreview').innerHTML='<span class="hint">กำลังโหลดรูป...</span>';try{const imgs=await req('/rest/v1/portfolio_images?project_id=eq.'+id+'&select=*&order=sort_order.asc');renderPortfolioImages(imgs,x.cover_url)}catch(e){renderPortfolioImages([],x.cover_url)}$('#portfolioDialog').showModal()};
window.editR=id=>{const x=rows.r.find(v=>v.id==id);$('#rId').value=x.id;$('#rService').value=x.service;$('#rStart').value=x.starting_price||'';$('#rUnit').value=x.unit_price||'';$('#rNote').value=x.note||'';$('#rPublished').checked=x.published;$('#priceDialog').showModal()};
window.editS=id=>{const x=rows.s.find(v=>v.id==id);$('#sId').value=x.id;$('#sTitle').value=x.title;$('#sDescription').value=x.description||'';$('#sImage').value='';showPreview('#serviceImagePreview',x.image_url);$('#sPublished').checked=x.published;$('#serviceDialog').showModal()};
async function upload(file){if(!file)return null;const doUpload=async()=>{const name=Date.now()+'-'+Math.random().toString(36).slice(2,7)+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=await fetch(url+'/storage/v1/object/portfolio/'+name,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+token,'Content-Type':file.type,'x-upsert':'false'},body:file});return {r,name}};let {r,name}=await doUpload();if(r.status===401||r.status===403){if(await refreshSession())({r,name}=await doUpload())}if(!r.ok)throw Error(await r.text());return url+'/storage/v1/object/public/portfolio/'+name}
$('#portfolioForm').onsubmit=async e=>{e.preventDefault();const oldId=$('#pId').value;let cover=oldId?(rows.p.find(x=>x.id==oldId)?.cover_url||null):null;const files=[...$('#pImage').files];try{const uploaded=[];for(const f of files){uploaded.push(await upload(f))}if(uploaded.length&&!cover)cover=uploaded[0];const data={title:$('#pTitle').value,scope:$('#pScope').value,category:$('#pCategory').value,year:+$('#pYear').value||null,location:$('#pLocation').value,cover_url:cover,description:$('#pDescription').value,featured:$('#pFeatured').checked,published:$('#pPublished').checked,updated_at:new Date().toISOString()};const saved=await save('portfolio',oldId,data);const projectId=oldId||saved?.[0]?.id;if(projectId&&uploaded.length){let existing=[];try{existing=await req('/rest/v1/portfolio_images?project_id=eq.'+projectId+'&select=id&order=sort_order.asc')}catch(_){};for(let i=0;i<uploaded.length;i++)await save('portfolio_images','',{project_id:+projectId,image_url:uploaded[i],sort_order:existing.length+i})}$('#portfolioDialog').close();await loadAll()}catch(err){alert('อัปโหลดไม่สำเร็จ: '+err.message)}};
$('#priceForm').onsubmit=async e=>{e.preventDefault();const id=$('#rId').value;await save('pricing',id,{service:$('#rService').value,starting_price:$('#rStart').value,unit_price:$('#rUnit').value,note:$('#rNote').value,published:$('#rPublished').checked,updated_at:new Date().toISOString()});$('#priceDialog').close();loadAll()};
$('#serviceForm').onsubmit=async e=>{e.preventDefault();const id=$('#sId').value;let image=id?(rows.s.find(x=>x.id==id)?.image_url||null):null;const f=$('#sImage').files[0];if(f)image=await upload(f);await save('services',id,{title:$('#sTitle').value,description:$('#sDescription').value,image_url:image,published:$('#sPublished').checked,updated_at:new Date().toISOString()});$('#serviceDialog').close();loadAll()};
async function save(table,id,data){return await req('/rest/v1/'+table+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(data)})}
window.del=async(table,id)=>{if(!confirm('ยืนยันการลบรายการนี้?'))return;try{const r=await fetch(url+'/rest/v1/'+table+'?id=eq.'+id,{method:'DELETE',headers:{...H(),Prefer:'return=representation'}});if(!r.ok)throw Error(await r.text());const deleted=await r.json();if(!deleted.length)throw Error('ระบบไม่ได้ลบข้อมูล อาจไม่มีสิทธิ์ลบรายการนี้');await loadAll()}catch(err){alert('ลบไม่สำเร็จ: '+err.message)}};boot();
function showPreview(sel,src){const el=$(sel);if(!el)return;el.innerHTML=src?'<img src="'+esc(src)+'" alt="preview">':''}
function fillSettings(a){const m=Object.fromEntries((a||[]).map(x=>[x.key,x.value||'']));[['setHeroTitle','hero_title'],['setHeroSubtitle','hero_subtitle'],['setPhone','phone'],['setEmail','email'],['setHq','hq_address'],['setContact','contact_address'],['setLine','line_url'],['setFacebook','facebook_url']].forEach(([id,k])=>{const e=$('#'+id);if(e)e.value=m[k]||''});window.siteSettings=m;showPreview('#heroImagePreview',m.hero_image_url);showPreview('#logoPreview',m.logo_url);showPreview('#logoMarkPreview',m.logo_mark_url)}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{const m=window.siteSettings||{};let hero=m.hero_image_url||'',logo=m.logo_url||'',mark=m.logo_mark_url||'';if($('#setHeroImageFile').files[0])hero=await upload($('#setHeroImageFile').files[0]);if($('#setLogoFile').files[0])logo=await upload($('#setLogoFile').files[0]);if($('#setLogoMarkFile').files[0])mark=await upload($('#setLogoMarkFile').files[0]);const pairs={hero_title:$('#setHeroTitle').value,hero_subtitle:$('#setHeroSubtitle').value,hero_image_url:hero,logo_url:logo,logo_mark_url:mark,phone:$('#setPhone').value,email:$('#setEmail').value,hq_address:$('#setHq').value,contact_address:$('#setContact').value,line_url:$('#setLine').value,facebook_url:$('#setFacebook').value};for(const [k,v] of Object.entries(pairs)){await req('/rest/v1/site_settings?key=eq.'+encodeURIComponent(k),{method:'PATCH',body:JSON.stringify({value:v,updated_at:new Date().toISOString()})})}$('#settingsMsg').textContent='บันทึกแล้ว';await loadAll()}catch(err){$('#settingsMsg').textContent='บันทึกไม่สำเร็จ: '+err.message}}

function renderPortfolioImages(imgs,cover){const el=$('#portfolioImagePreview');if(!el)return;const list=[...(imgs||[])];if(cover&&!list.some(x=>x.image_url===cover))list.unshift({image_url:cover,coverOnly:true});el.innerHTML=list.length?list.map((x,i)=>'<div class="thumb"><img src="'+esc(x.image_url)+'"><span>'+(x.image_url===cover?'หน้าปก':'รูป '+(i+1))+'</span>'+(x.id?'<button type="button" class="thumb-delete" onclick="deletePortfolioImage('+x.id+')">×</button>':'')+'</div>').join(''):'<span class="hint">ยังไม่มีรูป</span>'}
window.deletePortfolioImage=async id=>{if(!confirm('ลบรูปนี้ออกจากผลงาน?'))return;await req('/rest/v1/portfolio_images?id=eq.'+id,{method:'DELETE'});const pid=$('#pId').value;if(pid)await editP(+pid)}
$('#pImage').addEventListener('change',e=>{const files=[...e.target.files];const el=$('#portfolioImagePreview');if(!files.length)return;el.innerHTML=files.map((f,i)=>'<div class="thumb new"><img src="'+URL.createObjectURL(f)+'"><span>'+(i===0?'รูปที่เลือก 1':'รูปที่เลือก '+(i+1))+'</span></div>').join('')});
