const {url,key}=BANLANG;let token=localStorage.getItem('banlang_token')||'';const H=()=>({apikey:key,Authorization:'Bearer '+(token||key),'Content-Type':'application/json',Prefer:'return=representation'});
async function req(path,opt={}){const r=await fetch(url+path,{...opt,headers:{...H(),...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());const t=await r.text();return t?JSON.parse(t):[]}
async function login(email,password){const r=await fetch(url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw Error('อีเมลหรือรหัสผ่านไม่ถูกต้อง');const x=await r.json();token=x.access_token;localStorage.setItem('banlang_token',token)}
async function session(){if(!token)return false;const r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+token}});return r.ok}
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function boot(){if(await session()){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');await loadAll()}else{$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await login($('#email').value,$('#password').value);await boot()}catch(x){$('#loginMsg').textContent=x.message}};
$('#logout').onclick=()=>{localStorage.removeItem('banlang_token');token='';boot()};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#pageTitle').textContent=b.textContent});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function loadAll(){const [p,r,s]=await Promise.all([req('/rest/v1/portfolio?select=*&order=sort_order.asc,created_at.desc'),req('/rest/v1/pricing?select=*&order=sort_order.asc'),req('/rest/v1/services?select=*&order=sort_order.asc')]);window.rows={p,r,s};$('#portfolioCount').textContent=p.length;$('#priceCount').textContent=r.length;$('#serviceCount').textContent=s.length;
$('#portfolioList').innerHTML=p.map(x=>`<div class="row"><div><h3>${esc(x.title)}</h3><p>${esc(x.scope||'-')}</p><span class="tag">${x.published?'เผยแพร่':'ซ่อน'} · ${esc(x.category||'ไม่ระบุหมวด')}</span></div><div class="row-actions"><button class="muted" onclick="editP(${x.id})">แก้ไข</button><button class="danger" onclick="del('portfolio',${x.id})">ลบ</button></div></div>`).join('');
$('#priceList').innerHTML=r.map(x=>`<div class="row"><div><h3>${esc(x.service)}</h3><p>${esc(x.starting_price||'-')} · ${esc(x.unit_price||'-')}</p></div><div class="row-actions"><button class="muted" onclick="editR(${x.id})">แก้ไข</button><button class="danger" onclick="del('pricing',${x.id})">ลบ</button></div></div>`).join('');
$('#serviceList').innerHTML=s.map(x=>`<div class="row"><div><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p></div><div class="row-actions"><button class="muted" onclick="editS(${x.id})">แก้ไข</button><button class="danger" onclick="del('services',${x.id})">ลบ</button></div></div>`).join('')}
$('#newPortfolio').onclick=()=>{ $('#portfolioForm').reset();$('#pId').value='';$('#pPublished').checked=true;$('#portfolioDialog').showModal()};$('#newPrice').onclick=()=>{$('#priceForm').reset();$('#rId').value='';$('#rPublished').checked=true;$('#priceDialog').showModal()};$('#newService').onclick=()=>{$('#serviceForm').reset();$('#sId').value='';$('#sPublished').checked=true;$('#serviceDialog').showModal()};
window.editP=id=>{const x=rows.p.find(v=>v.id==id);$('#pId').value=x.id;$('#pTitle').value=x.title;$('#pScope').value=x.scope||'';$('#pCategory').value=x.category||'';$('#pYear').value=x.year||'';$('#pLocation').value=x.location||'';$('#pPublished').checked=x.published;$('#portfolioDialog').showModal()};
window.editR=id=>{const x=rows.r.find(v=>v.id==id);$('#rId').value=x.id;$('#rService').value=x.service;$('#rStart').value=x.starting_price||'';$('#rUnit').value=x.unit_price||'';$('#rNote').value=x.note||'';$('#rPublished').checked=x.published;$('#priceDialog').showModal()};
window.editS=id=>{const x=rows.s.find(v=>v.id==id);$('#sId').value=x.id;$('#sTitle').value=x.title;$('#sDescription').value=x.description||'';$('#sImage').value=x.image_url||'';$('#sPublished').checked=x.published;$('#serviceDialog').showModal()};
async function upload(file){if(!file)return null;const name=Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=await fetch(url+'/storage/v1/object/portfolio/'+name,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+token,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!r.ok)throw Error(await r.text());return url+'/storage/v1/object/public/portfolio/'+name}
$('#portfolioForm').onsubmit=async e=>{e.preventDefault();const id=$('#pId').value;let cover=id?(rows.p.find(x=>x.id==id)?.cover_url||null):null;const f=$('#pImage').files[0];if(f)cover=await upload(f);const data={title:$('#pTitle').value,scope:$('#pScope').value,category:$('#pCategory').value,year:+$('#pYear').value||null,location:$('#pLocation').value,cover_url:cover,published:$('#pPublished').checked,updated_at:new Date().toISOString()};await save('portfolio',id,data);$('#portfolioDialog').close();loadAll()};
$('#priceForm').onsubmit=async e=>{e.preventDefault();const id=$('#rId').value;await save('pricing',id,{service:$('#rService').value,starting_price:$('#rStart').value,unit_price:$('#rUnit').value,note:$('#rNote').value,published:$('#rPublished').checked,updated_at:new Date().toISOString()});$('#priceDialog').close();loadAll()};
$('#serviceForm').onsubmit=async e=>{e.preventDefault();const id=$('#sId').value;await save('services',id,{title:$('#sTitle').value,description:$('#sDescription').value,image_url:$('#sImage').value,published:$('#sPublished').checked,updated_at:new Date().toISOString()});$('#serviceDialog').close();loadAll()};
async function save(table,id,data){await req('/rest/v1/'+table+(id?'?id=eq.'+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(data)})}
window.del=async(table,id)=>{if(!confirm('ยืนยันการลบรายการนี้?'))return;await req('/rest/v1/'+table+'?id=eq.'+id,{method:'DELETE'});loadAll()};boot();